### ISSUE TITLE
Returning a false negative for Chrome Windows

### ISSUE THREAD

**Issue by luwes** [video-dev/can-autoplay#21]
Last week we allowed every browser to be checked by `can-autoplay` and we saw a visible drop in startup times. We could narrow it down to Chrome on Windows via metrics but we couldn't reproduce it ourselves.

cc @tenacex @fisherinnovation

**Comment by caiogondim** [comment]
One issue I had on production was that the default timeout was not enough, especially for mobile devices.
We were initially using 2 seconds, now using 5 seconds.

Could you try it with a bigger timeout?

**Comment by NicolasSiver** [comment]
@luwes you should conduct an experiment and try to find the best timeout. Default timeout will not work very well for the wide audience. The most severe impact when there is a cold-start. Like user clicks an URL from the email and it opens the browser, etc. Auto-play detection shares computation resources and timeout designed to prevent long detection, since it could be part of player's init phase.

Tuning and finding the best timeout for the platform is the way what I would recommend to do.

**Comment by luwes** [comment]
Thanks for your response guys! We're a little hesitant to do that because we put the autoplay check in between our main init flow. It updates a global autoplay flag basically which is used in different places.

**Comment by luwes** [comment]
Closing as it's an issue on our end, not the library.
